<a href="https://colab.research.google.com/github/ADITYASHANKER2801/Python/blob/main/numpy_Full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [5]:
#to convrt list into array
ar=np.array(l)

In [7]:
type(ar)

numpy.ndarray

In [8]:
#2d array
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
#Matrix by default 2 dimensionL DATASET
b=np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
a=np.array(l)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
c=a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
c[0]

1

In [17]:
c[0]=100

In [18]:
#When we did change in c or a we gave it as a reference but it is stored in the same location, it is known as swallow copy
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d=np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a[1]=400

In [23]:
a

array([100, 400,   3,   4])

In [24]:
#It doesnt show any changes as we copied the whole a into a new location so changing the original one wont affect it,it is known as deep copy
d

array([100,   2,   3,   4])

In [25]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
iterable=(i*i for i in range(5))

In [28]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
#convert strings into array and seprate on given type of delimiter
np.fromstring('234 456', sep=' ')

array([234., 456.])

**NUMPY- DATA TYPES**



In [30]:
l=[2,3,4,5,6]

In [31]:
ar=np.array(l)

In [32]:
ar.ndim

1

In [33]:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,3]])

In [34]:
ar2.ndim

2

In [35]:
ar.size

5

In [36]:
ar2.size

10

In [38]:
#Shape represents row and columns
ar.shape

(5,)

In [39]:
ar2.shape

(2, 5)

In [40]:
ar.dtype

dtype('int64')

In [41]:
ar22=np.array([(1.4,45,45),(6,8,9)])

In [42]:
#It shows float datatype as float consumes more space
ar22.dtype

dtype('float64')

In [43]:
#Range only takes integer as a input
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
#To do on float data types, we can also provide jump/skip values in it
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [45]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [46]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [47]:
#linspace divides the line into provided range and also divide them into equal spaces as provided
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
on=np.ones((2,3,2))

In [51]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [53]:
#To create an empty array
np.empty((3,5))

array([[3.69540105e-316, 0.00000000e+000, 1.06399913e+248,
        7.08171571e-077, 6.01099963e+175],
       [2.55867963e-086, 4.72709100e+180, 9.19596734e+170,
        9.82395831e+252, 8.69820675e+183],
       [1.39489187e-258, 6.01347002e-154, 6.24896858e-085,
        1.42731838e+228, 8.69555537e-322]])

In [54]:
#To make identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#To get log between given range just like linspace we can use logspace
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [60]:
arr=np.random.randn(3,4)

In [58]:
import pandas as pd

In [61]:
pd.DataFrame(arr)

0         1         2         3
0 -0.303241  0.384645  0.135243 -1.501320
1 -0.202575 -0.789325  2.020161  0.970278
2  1.474812  0.166456  1.767919 -0.769400

In [65]:
pd.DataFrame(np.random.randint(1,110, (3,4))).to_csv('data.csv')

In [66]:
pd.read_csv('data.csv')

Unnamed: 0   0   1    2    3
0           0  41  80  100  107
1           1  88  34   37   91
2           2  61  99    4    4

In [67]:
arr=np.random.rand(3,4)

In [68]:
#-1 means it is taking one dimension itself, keeping in mind that it should be equal to 3x4
arr.reshape(6,-1)

array([[0.43509223, 0.09164613],
       [0.49547282, 0.39122702],
       [0.32208792, 0.35865845],
       [0.82387099, 0.50647686],
       [0.24961752, 0.37870981],
       [0.35091599, 0.07580044]])

In [69]:
arr[2:5,1]

array([0.37870981])

In [74]:
arr1=np.random.randint(1,100, (3,3))

In [75]:
arr1

array([[87, 86, 59],
       [51, 12, 75],
       [38,  7, 68]])

In [76]:
arr1>50

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [80]:
arr1[arr1>50]

array([87, 86, 59, 51, 75, 68])

In [82]:
arr1[2:4, [1,2]]

array([[ 7, 68]])

In [85]:
#to do matrix multiplication
arr2=np.random.randint(1,70,(3,3))

In [86]:
arr1@arr2

array([[9810, 7683, 6135],
       [4986, 4527, 5451],
       [3888, 3878, 4790]])

In [89]:
col=np.array([[1,2,3,4]])

In [91]:
#To do transpose
col.T

array([[1],
       [2],
       [3],
       [4]])

In [92]:
np.sqrt(arr1)

array([[9.32737905, 9.2736185 , 7.68114575],
       [7.14142843, 3.46410162, 8.66025404],
       [6.164414  , 2.64575131, 8.24621125]])

In [93]:
np.exp(arr1)

array([[6.07603023e+37, 2.23524660e+37, 4.20121040e+25],
       [1.40934908e+22, 1.62754791e+05, 3.73324200e+32],
       [3.18559318e+16, 1.09663316e+03, 3.40427605e+29]])

In [94]:
np.log10(arr1)

array([[1.93951925, 1.93449845, 1.77085201],
       [1.70757018, 1.07918125, 1.87506126],
       [1.5797836 , 0.84509804, 1.83250891]])

In [95]:
arr1.flatten()

array([87, 86, 59, 51, 12, 75, 38,  7, 68])

In [96]:
arr3=np.array([1,2,3,4,5])

In [98]:
#Expands dimension from 1d to 2d
np.expand_dims(arr3, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [99]:
data=np.array([[1],[2],[3]])

In [100]:
data

array([[1],
       [2],
       [3]])

In [101]:
np.squeeze(data)

array([1, 2, 3])

In [102]:
#To repeat any element no. of times
np.repeat(arr1, 3)

array([87, 87, 87, 86, 86, 86, 59, 59, 59, 51, 51, 51, 12, 12, 12, 75, 75,
       75, 38, 38, 38,  7,  7,  7, 68, 68, 68])

In [104]:
#To shift array n times
np.roll(arr3,2)

array([4, 5, 1, 2, 3])

In [106]:
np.diag(arr3)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [107]:
~arr3

array([-2, -3, -4, -5, -6])

In [109]:
arr2=np.array([6,7,8,9,1])

In [110]:
arr2|arr3

array([ 7,  7, 11, 13,  5])

In [111]:
arr2>arr3

array([ True,  True,  True,  True, False])

In [113]:
arr4=np.array(["sudh","kush"])

In [114]:
np.char.upper(arr4)

array(['SUDH', 'KUSH'], dtype='<U4')

In [115]:
np.char.title(arr4)

array(['Sudh', 'Kush'], dtype='<U4')

In [116]:
np.char.capitalize(arr4)

array(['Sudh', 'Kush'], dtype='<U4')

In [117]:
np.mean(arr2)

6.2

In [118]:
np.median(arr2)

7.0

In [119]:
np.std(arr2)

2.7856776554368237

In [120]:
np.max(arr2)

9

In [121]:
np.min(arr2)

1

SORT,SEARCH,COUNT

In [122]:
arr5=np.array([4,3,5,6,77,8,1010,22,34,9,10])

In [123]:
np.sort(arr5)

array([   3,    4,    5,    6,    8,    9,   10,   22,   34,   77, 1010])

In [124]:
#To find the index of the searhced element
np.searchsorted(arr5, 34)

8

In [125]:
np.where(arr5>8)

(array([ 4,  6,  7,  8,  9, 10]),)

In [126]:
#Numpy matrix library

In [127]:
import numpy.matlib as nm

In [128]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [130]:
arr1=np.random.randint([[1,2],[3,4]])

In [131]:
arr2=np.random.randint([[5,6],[7,8]])

In [132]:
np.dot(arr1,arr2)

array([[ 6,  7],
       [16, 24]])

In [133]:
arr1@arr2

array([[ 6,  7],
       [16, 24]])